=== nhoople/netrunner-comprehensive-rules-data/schemas/node.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://nsg-cr.local/schemas/node.schema.json",
  "title": "CR node",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "kind",
    "number",
    "ref_type",
    "title",
    "parent_id",
    "child_ids",
    "text_markup",
    "text_plain",
    "spans",
    "examples",
    "is_new",
    "toc",
    "steps",
    "snippet_markup",
    "snippet_plain",
    "url"
  ],
  "properties": {
    "id": { "type": "string", "minLength": 1 },
    "kind": {
      "type": "string",
      "enum": [
        "chapter",
        "section",
        "subsection",
        "rule",
        "example",
        "timing_structure"
      ]
    },
    "number": { "type": "string", "minLength": 1 },
    "ref_type": { "type": "string" },
    "title": { "type": ["string", "null"] },
    "parent_id": { "type": ["string", "null"] },
    "child_ids": {
      "type": "array",
      "items": { "type": "string" }
    },
    "text_markup": { "type": "string" },
    "text_plain": { "type": "string" },
    "spans": {
      "type": "array",
      "items": { "$ref": "https://nsg-cr.local/schemas/span.schema.json" }
    },
    "examples": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": ["id", "text_markup", "text_plain", "is_new"],
        "properties": {
          "id": { "type": "string" },
          "text_markup": { "type": "string" },
          "text_plain": { "type": "string" },
          "is_new": { "type": "boolean" }
        }
      }
    },
    "is_new": { "type": "boolean" },
    "toc": { "type": "boolean" },
    "steps": { "type": "boolean" },
    "snippet_markup": { "type": ["string", "null"] },
    "snippet_plain": { "type": ["string", "null"] },
    "url": { "type": ["string", "null"] },
    "children": {
      "type": "array",
      "items": { "$ref": "#" }
    }
  }
}

=== nhoople/netrunner-comprehensive-rules-data/nodes/5.2.6h.json
{
  "id": "corp_basic_action_purge_virus_counters",
  "kind": "rule",
  "number": "5.2.6h",
  "ref_type": "rule",
  "title": null,
  "parent_id": "rule_corp_actions",
  "child_ids": [],
  "text_markup": "\"[click][click][click]: Purge virus counters.\" See {ref:rule_purge}.",
  "text_plain": "\"{click}{click}{click}: Purge virus counters.\" See rule 10.1.2.",
  "spans": [
    {
      "type": "symbol",
      "start": 1,
      "end": 8,
      "target": "click"
    },
    {
      "type": "symbol",
      "start": 8,
      "end": 15,
      "target": "click"
    },
    {
      "type": "symbol",
      "start": 15,
      "end": 22,
      "target": "click"
    },
    {
      "type": "ref",
      "start": 51,
      "end": 62,
      "ids": [
        "rule_purge"
      ],
      "combiner": "and"
    }
  ],
  "examples": [],
  "is_new": false,
  "toc": false,
  "steps": false,
  "snippet_markup": null,
  "snippet_plain": null,
  "url": "https://rules.nullsignal.games/?r=corp_basic_action_purge_virus_counters"
}

=== nhoople/netrunner-comprehensive-rules-data/nodes/9.9.9a.json
{
  "id": "rule_replacement_on_static_ability_must_remain_active",
  "kind": "rule",
  "number": "9.9.9a",
  "ref_type": "rule",
  "title": null,
  "parent_id": "rule_applying_replacement_effects",
  "child_ids": [
    "rule_replacement_on_static_ability_must_remain_active__example_1"
  ],
  "text_markup": "If a replacement effect modifies the effects of a static ability or the duration of a lingering effect, this modification applies continuously for as long as the replacement effect itself is active, and no longer applies once the replacement effect or the original effect being modified becomes inactive.",
  "text_plain": "If a replacement effect modifies the effects of a static ability or the duration of a lingering effect, this modification applies continuously for as long as the replacement effect itself is active, and no longer applies once the replacement effect or the original effect being modified becomes inactive.",
  "spans": [],
  "examples": [
    {
      "id": "rule_replacement_on_static_ability_must_remain_active__example_1",
      "text_markup": "{card:Gebrselassie}'s static ability replaces the durations of certain lingering effects affecting its host with a duration of \"for the remainder of the turn.\" If {card:Gebrselassie} is uninstalled or moved to a different host, its replacement effect no longer applies to those lingering effects, so they revert to their normal durations. If any of those durations have already expired, the corresponding effects will end at the next checkpoint.",
      "text_plain": "Gebrselassie's static ability replaces the durations of certain lingering effects affecting its host with a duration of \"for the remainder of the turn.\" If Gebrselassie is uninstalled or moved to a different host, its replacement effect no longer applies to those lingering effects, so they revert to their normal durations. If any of those durations have already expired, the corresponding effects will end at the next checkpoint.",
      "is_new": false
    }
  ],
  "is_new": false,
  "toc": false,
  "steps": false,
  "snippet_markup": null,
  "snippet_plain": null,
  "url": "https://rules.nullsignal.games/?r=rule_replacement_on_static_ability_must_remain_active"
}

=== nhoople/netrunner-comprehensive-rules-data/nodes/3.3.2.json
{
  "id": "rule_asset_rez_cost",
  "kind": "rule",
  "number": "3.3.2",
  "ref_type": "rule",
  "title": null,
  "parent_id": "sec_assets",
  "child_ids": [],
  "text_markup": "Assets are among the card types that have rez costs. They are installed unrezzed and remain inactive until the Corp rezzes them by paying their rez costs during a paid ability window. See {ref:sec_faceup_facedown_status}.",
  "text_plain": "Assets are among the card types that have rez costs. They are installed unrezzed and remain inactive until the Corp rezzes them by paying their rez costs during a paid ability window. See section 8.1.",
  "spans": [
    {
      "type": "ref",
      "start": 188,
      "end": 199,
      "ids": [
        "sec_faceup_facedown_status"
      ],
      "combiner": "and"
    }
  ],
  "examples": [],
  "is_new": false,
  "toc": false,
  "steps": false,
  "snippet_markup": null,
  "snippet_plain": null,
  "url": "https://rules.nullsignal.games/?r=rule_asset_rez_cost"
}

=== nhoople/netrunner-comprehensive-rules-data/nodes/9.8.6.json
{
  "id": "rule_unbroken_subroutines_target_for_break_abilities",
  "kind": "subsection",
  "number": "9.8.6",
  "ref_type": "section",
  "title": null,
  "parent_id": "sec_subroutines",
  "child_ids": [
    "rule_break_all_subroutines_no_targets",
    "rule_break_all_but_x_subroutines_targets"
  ],
  "text_markup": "Only unbroken subroutines can be chosen as targets for abilities that would break them.",
  "text_plain": "Only unbroken subroutines can be chosen as targets for abilities that would break them.",
  "spans": [],
  "examples": [],
  "is_new": false,
  "toc": false,
  "steps": false,
  "snippet_markup": null,
  "snippet_plain": null,
  "url": "https://rules.nullsignal.games/?r=rule_unbroken_subroutines_target_for_break_abilities"
}

=== nhoople/netrunner-comprehensive-rules-data/nodes/11.4_6_d.json
{
  "id": "sec_appendix_timing_structure_of_a_run_6_d",
  "kind": "timing_structure",
  "number": "11.4_6_d",
  "ref_type": "appendix",
  "title": null,
  "parent_id": "sec_appendix_timing_structure_of_a_run_6",
  "child_ids": [],
  "text_markup": "The run is complete.",
  "text_plain": "The run is complete.",
  "spans": [],
  "examples": [],
  "is_new": false,
  "toc": false,
  "steps": false,
  "snippet_markup": null,
  "snippet_plain": null,
  "url": "https://rules.nullsignal.games/?r=sec_appendix_timing_structure_of_a_run_6_d"
}

=== nhoople/netrunner-comprehensive-rules-data/nodes/9.1.6c.ex1.json
{
  "id": "rule_hosted_counter_used_condition__example_1",
  "kind": "example",
  "number": "9.1.6c.ex1",
  "ref_type": "example",
  "title": null,
  "parent_id": "rule_hosted_counter_used_condition",
  "child_ids": [],
  "text_markup": "The Runner spends the credit hosted on {card:Cyberfeeder} to pay the trigger cost of {card:Mimic}'s ability. Because the Runner triggered {card:Mimic}'s paid ability and {card:Cyberfeeder}'s ability allowed the credit to be spent, both {card:Mimic} and {card:Cyberfeeder} have been used.",
  "text_plain": "The Runner spends the credit hosted on Cyberfeeder to pay the trigger cost of Mimic's ability. Because the Runner triggered Mimic's paid ability and Cyberfeeder's ability allowed the credit to be spent, both Mimic and Cyberfeeder have been used.",
  "spans": [
    {
      "type": "card",
      "start": 39,
      "end": 50,
      "target": "Cyberfeeder",
      "card_code": "20006"
    },
    {
      "type": "card",
      "start": 78,
      "end": 83,
      "target": "Mimic",
      "card_code": "31008"
    },
    {
      "type": "card",
      "start": 124,
      "end": 129,
      "target": "Mimic",
      "card_code": "31008"
    },
    {
      "type": "card",
      "start": 149,
      "end": 160,
      "target": "Cyberfeeder",
      "card_code": "20006"
    },
    {
      "type": "card",
      "start": 208,
      "end": 213,
      "target": "Mimic",
      "card_code": "31008"
    },
    {
      "type": "card",
      "start": 218,
      "end": 229,
      "target": "Cyberfeeder",
      "card_code": "20006"
    }
  ],
  "examples": [],
  "is_new": false,
  "toc": false,
  "steps": false,
  "snippet_markup": null,
  "snippet_plain": null,
  "url": null
}

=== nhoople/netrunner-comprehensive-rules-data/nodes/6.1.4c.json
{
  "id": "rule_end_run_no_run_or_encounter",
  "kind": "rule",
  "number": "6.1.4c",
  "ref_type": "rule",
  "title": null,
  "parent_id": "rule_end_the_run",
  "child_ids": [
    "rule_end_run_no_run_or_encounter__example_1"
  ],
  "text_markup": "If an instruction to end the run resolves while there is neither a run nor an encounter in progress, that effect does nothing.",
  "text_plain": "If an instruction to end the run resolves while there is neither a run nor an encounter in progress, that effect does nothing.",
  "spans": [],
  "examples": [
    {
      "id": "rule_end_run_no_run_or_encounter__example_1",
      "text_markup": "The Corp plays {card:Unleash} and resolves the last subroutine on {card:Lycian Multi-Munition}. The Corp will gain 1[c], but there is no further effect.",
      "text_plain": "The Corp plays Unleash and resolves the last subroutine on Lycian Multi-Munition. The Corp will gain 1{c}, but there is no further effect.",
      "is_new": true
    }
  ],
  "is_new": true,
  "toc": false,
  "steps": false,
  "snippet_markup": null,
  "snippet_plain": null,
  "url": "https://rules.nullsignal.games/?r=rule_end_run_no_run_or_encounter"
}

=== nhoople/netrunner-comprehensive-rules-data/nodes/9.2.10a.json
{
  "id": "rule_mid_access_window_priority",
  "kind": "rule",
  "number": "9.2.10a",
  "ref_type": "rule",
  "title": null,
  "parent_id": "rule_mid_access_window",
  "child_ids": [],
  "text_markup": "A mid-access ability window gives only the Runner priority.",
  "text_plain": "A mid-access ability window gives only the Runner priority.",
  "spans": [],
  "examples": [],
  "is_new": false,
  "toc": false,
  "steps": false,
  "snippet_markup": null,
  "snippet_plain": null,
  "url": "https://rules.nullsignal.games/?r=rule_mid_access_window_priority"
}
